version: "3.8"
   
services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  django:
    build:
      context: ../django_backend
      dockerfile: Dockerfile
    image: django:local
    volumes:
      - ../django_backend/:/django-backend/
    ports:
      - "8080:8080"
    environment:
      - ENV=local
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postgres
    depends_on:
      - db

volumes:
    pgdata:
